# Base configs
baseurl: "https://adewaleafolabi.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Wale Afolabi"
subtitle: "The world as I see it!"
author: "Wale Afolabi"
header:
 title: "Photography"
 subtitle: "by Wale Afolabi"
footer:
 name: "Hey there, my name is Wale"
 bio: "I'm a developer trying to create an interest in photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  twitter: "https://www.twitter.com/adewale_afolabi"
  github: "https://www.github.com/adewaleafolabi"
